### PR TITLE
Add calibrate spectrum tool.

### PR DESCRIPTION
**Pull request by Brow71189**

### CODE REVIEW

**Comment by cmeyer** [comment]
Is this still a draft or final?

If final, can you add a line to CHANGELOG and add an appropriate test?

**Comment by cmeyer** [comment]
Is this now ready to review/merge?

**Comment by Brow71189** [comment]
Yes it is.

Chris Meyer ***@***.***> schrieb am Fr., 26. März 2021, 16:22:

**Comment by cmeyer** [comment]
Squashed/merged. 695b2334342e52fe65c1faeca3b59719d2c8b4c3. See also type checking 1393f7de77e1aa5c6b97104d19e32f6f9ae1093a additions.

**Comment by Brow71189** [comment]
Thanks!

**Pull request closed without merging**
