### PR TITLE
Added computation for aligning sequences of spectrum images.

### PR DESCRIPTION
**Pull request by Brow71189**

### CODE REVIEW

**Comment by cmeyer** [comment]
I do not think we should be using the computation UI any further. It is likely I'm going to break it soon and we need to replace it with something I can maintain and test.

**Comment by Brow71189** [comment]
Can we merge this so that it is available until we have a replacement for
the ComputationUI? The computation will still work even if the UI breaks,
you will only be stuck with the default parameters.

Chris Meyer <notifications@github.com> schrieb am Di., 14. Apr. 2020, 20:38:

**Comment by cmeyer** [comment]
Can you put this into experimental for now? I'm not sure this fits into EELS analysis.

**Comment by cmeyer** [comment]
As more explanation: I don't want EELS analysis to become a catch-all for things that belong elsewhere or things that should have a more general implementation. How is this PR different from what is provided in Swift? Does it really belong in EELS analysis or does it belong somewhere else eventually? If it eventually belongs somewhere else, I think it should go into experimental until the final location is figured out.

**Comment by Brow71189** [comment]
Closed because this will go into nion-software/experimental for now

**Pull request closed without merging**
